//ACTIONS FOR PRODUCTS
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
//ACTIONS FOR USER LOGIN AND REGISTER
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
//ACTIONS FOR USER CHECK INFOR
export const CHECK_USER_INFOR_SUCCESS = "CHECK_USER_INFOR_SUCCESS";
export const CHECK_USER_INFOR_FAIL = "CHECK_USER_INFOR_FAIL";
//ACTIONS FOR CLEAR ERR
export const CHECK_CLEAR_ERR = "CHECK_CLEAR_ERR";
export const USER_LOGOUT = "USER_LOGOUT";
export const CART_ACTIONS = "CART_ACTIONS";

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";
//ACTIONS FOR CATEGORIES
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
//ACTIONS FOR ORDERS
export const USER_CHECKOUT_REQUEST = "USER_CHECKOUT_REQUEST";
export const USER_CHECKOUT_SUCCESS = "USER_CHECKOUT_SUCCESS";
export const USER_CHECKOUT_FAIL = "USER_CHECKOUT_FAIL";
export const GET_ORDERS_USER = "GET_ORDERS_USER";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";
export const UPDATE_STATUS_ORDER = "UPDATE_STATUS_ORDER";
